export const LoginsActionTypes = {
  GET_CURRENT_LOGIN: "GET_CURRENT_LOGIN",
  SET_CURRENT_LOGIN: "SET_CURRENT_LOGIN",
  ADD_LOGIN: "ADD_LOGIN",
  SET_LOADING: "SET_LOADING",
  DELETE_LOGIN: "DELETE_LOGIN",
  UPDATE_LOGIN: "UPDATE_LOGIN",
  LOGINS_ERROR: "LOGINS_ERROR",
  SHOW_CURRENT_LOGIN: "SHOW_CURRENT_LOGIN"
};
