apiVersion: v1
kind: Service
metadata:
  name: front
  labels:
    app: front
spec:
  externalIPs:
  - 192.168.1.156
  - 88.196.63.92
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8010
  selector:
    app: front
  type: NodePort
