export const ChatsActionTypes = {
  GET_CHATS: "GET_CHATS",
  SET_CHAT: "SET_CHAT",
  ADD_CHAT: "ADD_CHAT",
  SET_LOADING: "SET_LOADING",
  DELETE_CHAT: "DELETE_CHAT",
  UPDATE_CHAT: "UPDATE_CHAT",
  CHAT_ERROR: "CHAT_ERROR"
};
