export const HeaderActionTypes = {
  GET_CURRENT_HEADER: "GET_CURRENT_HEADER",
  SET_CURRENT_HEADER: "SET_CURRENT_HEADER",
  ADD_HEADER: "ADD_HEADER",
  SET_LOADING: "SET_LOADING",
  DELETE_HEADER: "DELETE_HEADER",
  UPDATE_HEADER: "UPDATE_HEADER",
  HEADER_ERROR: "HEADER_ERROR",
  SHOW_CURRENT: "SHOW_CURRENT"
};
