export const SettingsActionTypes = {
  GET_CURRENT_SETTINGS: "GET_CURRENT_SETTINGS",
  SET_CURRENT_SETTINGS: "SET_CURRENT_SETTINGS",
  SET_LOADING: "SET_LOADING",
  SETTINGS_ERROR: "SETTINGS_ERROR"
};
