export const UserActionTypes = {
  SET_CURRENT: "SET_CURRENT",
  CLEAR_CURRENT: "CLEAR_CURRENT",
  ADD_USER: "ADD_USER",
  GET_USERS: "GET_USERS",
  GET_USER: "GET_USER",
  DELETE_USER: "DELETE_USER",
  UPDATE_USER: "UPDATE_USER",
  SET_LOADING: "SET_LOADING",
  USER_ERROR: "USER_ERROR",
  USER_LOGIN: "USER_LOGIN",
  GET_CURRENT: "GET_CURRENT"
};
